<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.28.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.24" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.24" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.9" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Restaurant.Application\Restaurant.Application.csproj" />
    <ProjectReference Include="..\Restaurant.Domain\Restaurant.Domain.csproj" />
    <ProjectReference Include="..\Restaurant.Persistence\Restaurant.Persistence.csproj" />
  </ItemGroup>

</Project>
